version: '3.1'
services:
  challenge_app:
    container_name: storeapi_app
    image: springboot-postgresql
    build: .
    depends_on:
      - compose_db
    network_mode: host
    restart: always

  compose_db:
    container_name: storeapi_db
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storeapi_db
    restart: always

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local